# Generated by Django 3.1.1 on 2020-09-05 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('digital_marketing', 'Digital Marketing'), ('social_media', 'Social Media Marketing'), ('web_designing', 'Web Designing'), ('graphic_designing', 'Graphic Designing'), ('identity_designing', 'Identity Designing'), ('web_development', 'Web Development'), ('mobile_development', 'Mobile App Development')], max_length=40)),
                ('client', models.CharField(max_length=60)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('team_alloted', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.team')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='projects.project')),
            ],
        ),
    ]
